name: Run tests

on:
  workflow_dispatch:
    inputs:
      testName:
        description: 'Part of the test name to run'
        required: false
        default: ''
      workersCount:
        description: 'Workers Count'
        required: false
        default: '1'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Build & Install
        run: dotnet build
        
      - name: Ensure browsers are installed
        run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.testName }}" != "" ]; then
            echo "Running tests filtered by name: '${{ github.event.inputs.testName }}' with workers count = ${{ github.event.inputs.workersCount }}"
            dotnet test
              --filter "Name~${{ github.event.inputs.testName }}" \
              -- NUnit.NumberOfTestWorkers=${{ github.event.inputs.workersCount }} \
              --logger:"trx;LogFileName=TestResults/results.trx"
          else
            echo "Running all tests with workers count = ${{ github.event.inputs.workersCount }}"
            dotnet test
              -- NUnit.NumberOfTestWorkers=${{ github.event.inputs.workersCount }} \
              --logger:"trx;LogFileName=TestResults/results.trx"
          fi

      - name: Ensure TestResults directory exists
        run: mkdir -p TestResults

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-dotnet-test-results
          path: TestResults/
          retention-days: 7
