name: Run tests

on:
  workflow_dispatch:
    inputs:
      testName:
        description: 'Part of the test name to run'
        required: false
        default: ''
      workersCount:
        description: 'Workers Count'
        required: false
        default: '1'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.50.0-jammy
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet publish ./Playwright.NET/Playwright.NET.csproj -c Release --no-restore
      
      - name: Install Playwright Browsers
        run: ./Playwright.NET/bin/Release/net8.0/playwright.sh install
      
      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.testName }}" != "" ]; then
          echo "Running tests filtered by name: '${{ github.event.inputs.testName }}' with workers count = ${{ github.event.inputs.workersCount }}"
          dotnet test ./Playwright.NET/Playwright.NET.csproj --no-build --configuration Release --filter "Name~${{ github.event.inputs.testName }}" -- NUnit.NumberOfTestWorkers=${{ github.event.inputs.workersCount }}
          else
          echo "Running all tests with workers count = ${{ github.event.inputs.workersCount }}"
          dotnet test ./Playwright.NET/Playwright.NET.csproj --no-build --configuration Release -- NUnit.NumberOfTestWorkers=${{ github.event.inputs.workersCount }}
          fi

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-dotnet-test-results
          path: TestResults/
          retention-days: 7
